# Generated by Django 3.0.6 on 2020-05-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('correo', models.EmailField(max_length=254, verbose_name='correo')),
                ('ciudad', models.CharField(blank=True, choices=[('gye', 'Guayaquil')], max_length=50, verbose_name='ciudad')),
                ('sector', models.CharField(choices=[('sur', 'Sur'), ('sur_e', 'Sur-Este'), ('cen', 'Centro'), ('nor', 'Norte'), ('samb', 'Samborondon')], max_length=50, verbose_name='sector')),
                ('direccion', models.CharField(max_length=500, verbose_name='direccion')),
                ('telefono', models.CharField(max_length=10, verbose_name='telefono')),
            ],
        ),
    ]
